# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genomicsdb_callsets_mapping.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!genomicsdb_callsets_mapping.proto\"\x87\x01\n\x15SampleIDToTileDBIDMap\x12\x13\n\x0bsample_name\x18\x01 \x02(\t\x12\x0f\n\x07row_idx\x18\x02 \x02(\x03\x12\x13\n\x0bidx_in_file\x18\x03 \x02(\x03\x12\x15\n\x0bstream_name\x18\x04 \x01(\tH\x00\x12\x12\n\x08\x66ilename\x18\x05 \x01(\tH\x00\x42\x08\n\x06source\"<\n\x10\x43\x61llsetMappingPB\x12(\n\x08\x63\x61llsets\x18\x01 \x03(\x0b\x32\x16.SampleIDToTileDBIDMapB=\n\x14org.genomicsdb.modelB\x1aGenomicsDBCallsetsMapProtoZ\tprotobuf/')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genomicsdb_callsets_mapping_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.genomicsdb.modelB\032GenomicsDBCallsetsMapProtoZ\tprotobuf/'
  _SAMPLEIDTOTILEDBIDMAP._serialized_start=38
  _SAMPLEIDTOTILEDBIDMAP._serialized_end=173
  _CALLSETMAPPINGPB._serialized_start=175
  _CALLSETMAPPINGPB._serialized_end=235
# @@protoc_insertion_point(module_scope)
