# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genomicsdb_vid_mapping.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgenomicsdb_vid_mapping.proto\"u\n FieldLengthDescriptorComponentPB\x12$\n\x1avariable_length_descriptor\x18\x01 \x01(\tH\x00\x12\x16\n\x0c\x66ixed_length\x18\x02 \x01(\x05H\x00\x42\x13\n\x11length_descriptor\"\x90\x02\n\x13GenomicsDBFieldInfo\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x03(\t\x12\x17\n\x0fvcf_field_class\x18\x03 \x03(\t\x12\x10\n\x08vcf_type\x18\x04 \x01(\t\x12\x31\n\x06length\x18\x05 \x03(\x0b\x32!.FieldLengthDescriptorComponentPB\x12\x15\n\rvcf_delimiter\x18\x06 \x03(\t\x12#\n\x1bVCF_field_combine_operation\x18\x07 \x01(\t\x12\x10\n\x08vcf_name\x18\x08 \x01(\t\x12\x31\n\"disable_remap_missing_with_non_ref\x18\t \x01(\x08:\x05\x66\x61lse\"H\n\nChromosome\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06length\x18\x02 \x02(\x03\x12\x1c\n\x14tiledb_column_offset\x18\x03 \x02(\x03\"R\n\x0cVidMappingPB\x12$\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x14.GenomicsDBFieldInfo\x12\x1c\n\x07\x63ontigs\x18\x02 \x03(\x0b\x32\x0b.ChromosomeB8\n\x14org.genomicsdb.modelB\x15GenomicsDBVidMapProtoZ\tprotobuf/')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genomicsdb_vid_mapping_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.genomicsdb.modelB\025GenomicsDBVidMapProtoZ\tprotobuf/'
  _FIELDLENGTHDESCRIPTORCOMPONENTPB._serialized_start=32
  _FIELDLENGTHDESCRIPTORCOMPONENTPB._serialized_end=149
  _GENOMICSDBFIELDINFO._serialized_start=152
  _GENOMICSDBFIELDINFO._serialized_end=424
  _CHROMOSOME._serialized_start=426
  _CHROMOSOME._serialized_end=498
  _VIDMAPPINGPB._serialized_start=500
  _VIDMAPPINGPB._serialized_end=582
# @@protoc_insertion_point(module_scope)
