name: Build Wheels

on: [push] # add pull as well

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        #with:
        #  fetch-depth: 0  # Optional, use if you use setuptools_scm
        #  submodules: true  # Optional, use if you have submodules

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

#   upload_all:
#     needs: [build_wheels,make_sdist]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/download-artifact@v3
#       with:
#         name: artifact
#         path: dist

#     - name: Publish package to TestPyPI
#       uses: pypa/gh-action-pypi-publish@release/v1
#       with:
#         password: ${{ secrets.TESTPYPI }}
#         repository-url: https://test.pypi.org/legacy/