name: Build And Publish Wheels

on:
  push:
    tags:
      - v*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:
      - uses: actions/checkout@v4

      - name: Set version number
        run: |
            VERSION_NUMBER=${GITHUB_REF_NAME:1}
            if [ $(echo "${VERSION_NUMBER##*.}") == "test" ]; then
                VERSION_NUMBER=${VERSION_NUMBER%.*}
            fi
            echo ${VERSION_NUMBER} >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
            CIBW_CONFIG_SETTINGS: "--build-option=--with_version=$VERSION_NUMBER"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_all:
    name: Publish wheels
    needs: [build_wheels,make_sdist]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - name: Publish package to TestPyPI
      if: ${{ contains(github.ref_name,'.test') }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TESTPYPI }}
        repository-url: https://test.pypi.org/legacy/
    
    - name: Publish package to PyPI
      if: ${{ !contains(github.ref_name,'.test') }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI }}